backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "staticContent"
    label: "Static Content"
    files:
      - file: "content/index/index.md"
        label: "Front Page"
        name: "frontpage"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Front Page Image', name: 'image', widget: 'image' }
          - { label: 'Severe Weather Image', name: 'severeWeatherImage', widget: 'image' }
          - { label: 'Wildland Fire Image', name: 'wildlandFireImage', widget: 'image' }
          - { label: 'Insects and Diseases Image', name: 'insectsAndDiseasesImage', widget: 'image' }
          - { label: 'Landscape Diversity Image', name: 'landscapeDiversityImage', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: "content/severeWeather.md"
        name: 'severeWeather'
        label: 'Severe Weather'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: "content/wildlandFire.md"
        name: 'wildlandFire'
        label: 'Wildland Fire'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: "content/insectsAndDiseases.md"
        name: 'insectsAndDiseases'
        label: 'Insects and Diseases'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: "content/landscapeDiversity.md"
        name: 'landscapeDiversity'
        label: 'Landscape Diversity'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: "severeWeather"
    label: "Severe Weather"
    folder: "content/severeWeather"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: Images, name: images, widget: list, field: { name: image, label: Image, widget: image }}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "wildlandFire"
    label: "Wildland Fire"
    folder: "content/wildlandFire"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: Images, name: images, widget: list, field: { name: image, label: Image, widget: image }}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "insectsAndDiseases"
    label: "Insects and Diseases"
    folder: "content/insectsAndDiseases"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: Images, name: images, widget: list, field: { name: image, label: Image, widget: image }}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "landscapeDiversity"
    label: "Landscape Diversity"
    folder: "content/landscapeDiversity"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: Images, name: images, widget: list, field: { name: image, label: Image, widget: image }}
      - {label: "Body", name: "body", widget: "markdown"}